name: valotod_app
description: A Very Good Project created by Very Good CLI.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=3.1.0 <4.0.0"

dependencies:
  avatar_glow: ^2.0.2
  bloc: ^8.1.2
  dartz: ^0.10.1
  dio: ^5.3.3
  dot_navigation_bar: ^1.0.2
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  flutter_gen_runner: ^5.3.1
  flutter_localizations:
    sdk: flutter
  font_awesome_flutter: ^10.6.0
  gap: ^3.0.1
  get: ^4.6.6
  get_it: ^7.6.4
  google_fonts: ^6.1.0
  google_nav_bar: ^5.0.6
  intl: ^0.18.1
  json_annotation: ^4.8.1
  mockito: ^5.4.2
  percent_indicator: ^4.2.3
  photo_view: ^0.14.0
  pretty_dio_logger: ^1.3.1
  provider: ^6.0.5
  shared_preferences: ^2.2.2

dev_dependencies:
  bloc_test: ^9.1.4
  build_runner: ^2.4.6
  flutter_native_splash: ^2.3.8
  flutter_test:
    sdk: flutter
  json_serializable: ^6.7.1
  mocktail: ^1.0.0
  very_good_analysis: ^5.1.0

flutter_native_splash:
  color: "#ffffff"
  image: "assets/img/splash.png"
  android: true
  ios: true

flutter:
  fonts:
    - family: Montserrat
      fonts:
        - asset: assets/font/Roboto-Medium.ttf
  uses-material-design: true
  generate: true
  assets:
    - assets/img/
    - assets/font/
    - assets/gif/
